apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default

  source:
    repoURL:repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 65.0.0         
    path: monitoring                
    helm:
      releaseName: monitoring
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: monitor

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
