apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        # Existing application container
        - name: quran-app
          image: yoyo7sniper97/quran-app-argo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5050

        # Prometheus metrics sidecar
        - name: nginx-exporter
          image: nginx/nginx-prometheus-exporter:0.14.0
          args:
            - "-nginx.scrape-uri=http://localhost:5050/nginx_status"
          ports:
            - name: metrics
              containerPort: 9113
