apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        # Existing application container
        - name: quran-app
          image: yoyo7sniper97/quran-app-argo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5050
